name = "HugoTeX"
license = "MIT"
licenselink = "https://github.com/shiva/HugoTeX/blob/master/LICENSE"
description = "LaTeX style hugo theme"
homepage = "https://blog.shiv.me/theme"
tags = ["blog", "minimal", "simple", "LaTeX"]
features = ["minimal", "simple", "responsive", "syntax highlight", "LaTeX"]
min_version = "0.60.1"

[author]
  name = "HelloRuskClone"
  homepage = "https://blog.shiv.me/"
